root: true

extends:
  - pegasus
  - pegasus/browser
  - pegasus/node

rules:
  no-warning-comments: off

overrides:
  - files:
      - '**/*.ts'
    extends:
      - pegasus/typescript
      - plugin:prettier/recommended
    parserOptions:
      project: './tsconfig.json'

  - files:
      - '**/*.tsx'
    extends:
      - pegasus/typescript
      - pegasus/react
      - plugin:prettier/recommended
    parserOptions:
      project: './tsconfig.eslint.json'

  - files:
      - '*.stories.@(ts|tsx|js|jsx|mjs|cjs)'
    extends:
      - plugin:storybook/recommended
      - pegasus/typescript
      - pegasus/react
      - plugin:prettier/recommended
    parserOptions:
      project: './tsconfig.eslint.json'

ignorePatterns:
  - '!.storybook/'
